### ISSUE TITLE
critical information expose /auth/user/register

### ISSUE THREAD

**Issue by vidhi2810** [ale-sanchez-g/villain#33] opened 2022-02-28 23:22 UTC
critical information like routine name, constraint, table name etc expose to api
Actual:

![image](https://user-images.githubusercontent.com/20989368/156075252-096a2da0-d59c-4cf0-ae89-34bf7a7e746b.png)

payload:
POST https://supervillain.herokuapp.com/auth/user/register
400
2.10 s
POST /auth/user/register HTTP/1.1
Authorization: TOKEN
Content-Type: application/json
User-Agent: PostmanRuntime/7.26.8
Accept: /
Cache-Control: no-cache
Postman-Token: 789d4104-59a1-4f3a-9adf-c26e13c3eaf9
Host: supervillain.herokuapp.com
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 50
{
"username": "abc",
"password": "testPW"
}
HTTP/1.1 400 Bad Request
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 260
Etag: W/"104-QzjKPVIrp1ZCPHjxWDd4t19kOxY"
Date: Mon, 28 Feb 2022 23:19:04 GMT
Via: 1.1 vegur
{"error":{"name":"error","length":sample,"severity":"ERROR","code":"23505","detail":"Key (username)=(abc) already exists.","schema":"public","table":"sample","constraint":"sample","file":"sample.c","line":"sample","routine":"sample"}}

**Comment by ale-sanchez-g** [comment] 2022-03-01 01:47
duplicate of #32

**Closed by ale-sanchez-g** 2022-03-01 01:47 UTC
Labels: bug
